// <auto-generated />
using System;
using CarRentalConsole.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalConsole.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CarRentalConsole.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyRate = 120m,
                            IsAvailable = true,
                            Name = "Toyota Camry"
                        },
                        new
                        {
                            Id = 2,
                            DailyRate = 115m,
                            IsAvailable = true,
                            Name = "Honda Accord"
                        },
                        new
                        {
                            Id = 3,
                            DailyRate = 180m,
                            IsAvailable = true,
                            Name = "Ford Mustang"
                        },
                        new
                        {
                            Id = 4,
                            DailyRate = 105m,
                            IsAvailable = true,
                            Name = "Chevrolet Malibu"
                        },
                        new
                        {
                            Id = 5,
                            DailyRate = 110m,
                            IsAvailable = true,
                            Name = "Nissan Altima"
                        },
                        new
                        {
                            Id = 6,
                            DailyRate = 90m,
                            IsAvailable = true,
                            Name = "Hyundai Elantra"
                        },
                        new
                        {
                            Id = 7,
                            DailyRate = 130m,
                            IsAvailable = true,
                            Name = "Kia Sportage"
                        },
                        new
                        {
                            Id = 8,
                            DailyRate = 170m,
                            IsAvailable = true,
                            Name = "Jeep Wrangler"
                        },
                        new
                        {
                            Id = 9,
                            DailyRate = 220m,
                            IsAvailable = true,
                            Name = "BMW 320i"
                        },
                        new
                        {
                            Id = 10,
                            DailyRate = 250m,
                            IsAvailable = true,
                            Name = "Mercedes-Benz C300"
                        });
                });

            modelBuilder.Entity("CarRentalConsole.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CarRentalConsole.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("CarRentalConsole.Models.Rental", b =>
                {
                    b.HasOne("CarRentalConsole.Models.Car", "Car")
                        .WithMany("Rentals")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRentalConsole.Models.Customer", "Customer")
                        .WithMany("Rentals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CarRentalConsole.Models.Car", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CarRentalConsole.Models.Customer", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
